# Generated by Django 3.2.5 on 2021-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
