# Generated by Django 3.2.5 on 2021-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
