# Generated by Django 3.2.5 on 2021-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
