# Generated by Django 3.2.5 on 2021-08-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripeCustomerID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
