# Generated by Django 3.2.5 on 2021-08-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_client_stripecustomerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sub_status',
            field=models.BooleanField(default=False),
        ),
    ]
