# Generated by Django 3.2.5 on 2021-08-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_client_sub_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripeCustomerID', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='stripeCustomerID',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sub_status',
        ),
        migrations.AddField(
            model_name='client',
            name='monAbonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.monabonnement'),
        ),
    ]
