# Generated by Django 3.2.5 on 2021-08-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210804_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.video')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='mesVideos',
            field=models.ManyToManyField(blank=True, to='api.MonVideo'),
        ),
    ]
