# Generated by Django 3.2.5 on 2021-08-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210805_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mesVideos',
            field=models.ManyToManyField(blank=True, null=True, to='api.MonVideo'),
        ),
    ]
