# Generated by Django 3.2.5 on 2021-08-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_client_mesvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='monvideo',
            name='mode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monvideo',
            name='payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='mesVideos',
            field=models.ManyToManyField(blank=True, to='api.MonVideo'),
        ),
    ]
